-
  why: Demo how document.json can use $ref and $def.
  url: /test_subject.json
  find:
    -
      schema: schemas/document.json
-
  url: /test_subject.json
  find:
    -
      schema: schemas/is_object.json
    -
      schema: schemas/is_array.json
      matches: false

-
  url: /test_subject.json
  find:
    -
      schema: schemas/is_array.json
      path: lorem.ipsum
-
  url: /test_subject.json
  find:
    -
      schema: '{"type":"array"}'
      path: lorem.ipsum
-
  url: /test_subject.json
  find:
    -
      schema: schemas/is_object.json
      matches: true
    -
      schema: schemas/is_foo.json
      matches: true
    -
      schema: schemas/is_array.json
      matches: false
