#!/usr/bin/env php
<?php

/**
 * @file
 *
 * This is the CLI controller for check_pages
 */

use AKlump\LoftLib\Bash\Color;

define('ROOT', __DIR__);

// Find and load the autoloader
$autoloaders = [
  ROOT . '/vendor/autoload.php',
  ROOT . '/../../../vendor/autoload.php',
];
while ($autoloader = array_shift($autoloaders)) {
  if (file_exists($autoloader)) {
    require_once $autoloader;
    break;
  }
  if (empty($autoloaders)) {
    echo "Could not find autoload.php" . PHP_EOL;
    exit(2);
  }
}

try {
  require ROOT . '/includes/bootstrap.inc';
  $test = $app->getTest();
  echo Color::wrap('blue', sprintf('Running test "%s"', strtoupper(basename($test)))) . PHP_EOL;
  $app->runTest($test);
}
catch (\Exception $exception) {
  echo PHP_EOL;
  echo Color::wrap('red', $exception->getMessage() . PHP_EOL . PHP_EOL);
  exit(1);
}

echo PHP_EOL;
echo Color::wrap('green', 'Test complete.') . PHP_EOL . PHP_EOL;
exit(0);
