#!/usr/bin/env php
<?php

/**
 * @file
 *
 * This is the CLI controller for check_pages
 */

use AKlump\LoftLib\Bash\Color;

define('ROOT', __DIR__);

global $app;
global $cli;
global $test_runner;

$start_time = microtime(TRUE);

// Find and load the autoloader
$autoloaders = [
  ROOT . '/vendor/autoload.php',
  ROOT . '/../../../vendor/autoload.php',
];
while ($autoloader = array_shift($autoloaders)) {
  if (file_exists($autoloader)) {
    require_once $autoloader;
    break;
  }
  if (empty($autoloaders)) {
    echo "Could not find autoload.php" . PHP_EOL;
    exit(2);
  }
}

try {
  require ROOT . '/includes/bootstrap.inc';
  $filters = array_filter(explode(' ', $cli->getParam('filter', '')));
  foreach ($filters as $filter) {
    $app->addSuiteFilter($filter);
  }
  $app->executeRunner($test_runner);
}

  // Finish with an error response.
catch (\Exception $exception) {
  // Shift the first line so only that is red, in case we want to dump a
  // pretty-print JSON variable.
  $lines = explode(PHP_EOL, $exception->getMessage());
  echo PHP_EOL;
  echo Color::wrap('white on red', array_shift($lines)) . PHP_EOL;
  echo implode(PHP_EOL, $lines) . PHP_EOL . PHP_EOL;
  exit(1);
}

// Calculate the elapsed time.
$elapsed = microtime(TRUE) - $start_time;
if ($elapsed < 60) {
  $elapsed = round($elapsed, 1) . ' seconds';
}
else {
  $elapsed = round($elapsed / 60, 1) . ' minutes';
}

// Finish with a happy response.
echo PHP_EOL;
echo Color::wrap('white on green', "Testing completed successfully in $elapsed.") . PHP_EOL . PHP_EOL;
exit(0);
