#!/usr/bin/env php
<?php
/**
 * @file
 * Entry file for Check Pages CLI.
 */

use AKlump\CheckPages\Command\InitCommand;
use AKlump\CheckPages\Command\RunCommand;
use AKlump\CheckPages\Files\LocalFilesProvider;
use AKlump\CheckPages\Handlers\AddHandlerAutoloads;
use AKlump\CheckPages\Helpers\BuildContainer;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputOption;

foreach ([
           __DIR__ . '/../../autoload.php',
           __DIR__ . '/../vendor/autoload.php',
           __DIR__ . '/vendor/autoload.php',
         ] as $file) {
  if (file_exists($file)) {
    /** @var \Composer\Autoload\ClassLoader $class_loader */
    $class_loader = require_once $file;
    break;
  }
}
if (!isset($class_loader)) {
  throw new RuntimeException('Missing autoload.php');
}

$root_files = new LocalFilesProvider(__DIR__);

global $container;
$container = (new BuildContainer($root_files))();

// TODO Can this be optimized and cached in an autoload.php?
$handlers_manager = $container->get('handlers_manager');
(new AddHandlerAutoloads($handlers_manager))($class_loader);

$application = new Application();
$application->setName('Check Pages by In the Loft Studios');

$composer_json = $root_files->tryResolveFile('composer.json')[0];
$version = json_decode(file_get_contents($composer_json))->version ?? '';
$application->setVersion($version);

$application->add(new RunCommand($root_files));
$application->add(new InitCommand(__DIR__ . '/init_scaffold'));

// Expose commands to plugins via events.
foreach ($application->all() as $command) {
  if ($command->getName() === 'run') {
    $command->addOption('debug', NULL, InputOption::VALUE_OPTIONAL);
  }
}

$application->run();
