services:
  suite_validator:
    class: \AKlump\CheckPages\SuiteValidator
    tags:
      - { name: event_subscriber }
  response_files:
    class: \AKlump\CheckPages\Output\SaveResponseToFile
    tags:
      - { name: event_subscriber }
  feedback:
    class: \AKlump\CheckPages\Output\Feedback
    tags:
      - { name: event_subscriber }
  retest:
    class: \AKlump\CheckPages\Service\Retest
    tags:
      - { name: event_subscriber }
  suite_index:
    class: \AKlump\CheckPages\Service\SuiteIndexService
    tags:
      - { name: event_subscriber }
  config_secrets:
    class: \AKlump\CheckPages\Service\SecretsService
    tags:
      - { name: event_subscriber }
  interpolator:
    class: \AKlump\CheckPages\Service\InterpolationService
    tags:
      - { name: event_subscriber }
