services:
  response_files:
    class: \AKlump\CheckPages\Output\SaveResponseToFile
    tags:
      - { name: event_subscriber }
  feedback:
    class: \AKlump\CheckPages\Output\Feedback
    tags:
      - { name: event_subscriber }
  retest:
    class: \AKlump\CheckPages\Service\Retest
    tags:
      - { name: event_subscriber }
