<?php

namespace AKlump\CheckPages\Plugin;

use AKlump\LoftLib\Code\Strings;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Yaml\Yaml;

final class PluginsCompiler {

  /**
   * @var string
   */
  private $masterSchemaPath;

  /**
   * @var \AKlump\CheckPages\Plugin\PluginsManager
   */
  private $pluginsManager;

  /**
   * @var array
   */
  private $schema;

  /**
   * @var string
   */
  private $examplesPath;

  /**
   * @var string
   */
  private $generatedSchemaPath;

  /**
   * PluginsCompiler constructor.
   *
   * @param string $plugins_dir
   * @param string $master_schema_path
   *   The path to the base schema to load as the template; plugins are merged
   *   into this.  This schema is what is editable by developers.
   * @param string $generated_schema_path
   *   The output schema path, with plugins compiled in.
   * @param string $examples_path
   *   The path to the projects demo/example files.
   */
  public function __construct(
    PluginsManager $plugins_manager,
    string $master_schema_path,
    string $generated_schema_path,
    string $master_services_path,
    string $generated_services_path,
    string $examples_path
  ) {
    $this->pluginsManager = $plugins_manager;

    $this->masterServicesPath = $master_services_path;
    $this->generatedServicesPath = $generated_services_path;
    $this->services = Yaml::parseFile($this->masterServicesPath);

    $this->masterSchemaPath = $master_schema_path;
    $this->schema = ['readyOnly' => TRUE] + $this->loadJson($master_schema_path);
    $description = $this->schema['description'] ?? '';
    $description .= '  DO NOT EDIT THIS FILE.  AUTO-GENERATED FROM ' . basename($master_schema_path);
    $this->schema = array_filter([
        '$schema' => $this->schema['$schema'] ?? NULL,
        'title' => $this->schema['title'] ?? NULL,
        'description' => trim($description),
      ]) + $this->schema;

    $this->generatedSchemaPath = $generated_schema_path;
    $this->examplesPath = $examples_path;
  }

  /**
   * Compile all plugins into the app.
   */
  public function compile() {
    $plugins = $this->pluginsManager->getAllPlugins();
    foreach ($plugins as &$plugin) {
      $this->compilePlugin($plugin);
    }
    $this->createTestRunnerPhpFile($plugins);
    $this->generateServicesFile();

    // This has to come last so plugins may affect the compile files.
    foreach ($plugins as &$plugin) {
      if (file_exists($plugin['path'] . '/compile.php')) {
        $plugin_dir = $plugin['path'];
        $compile_dir = $this->examplesPath;
        $result = require $plugin['path'] . '/compile.php';
        if (!$result) {
          throw new \RuntimeException(sprintf("Compilation failed in %s.", $plugin['path'] . '/compile.php'));
        }
      }
    }
  }

  private function createTestRunnerPhpFile($plugins) {
    $runner_code = [
      '<?php',
      "/** AUTOGENERATED DO NOT EDIT */",
      "add_directory(__DIR__ . '/plugins');",
      "load_config('config/local');",
    ];

    foreach ($plugins as $plugin) {
      if ($plugin['has_tests']) {
        $runner_code[] = "run_suite('{$plugin['id']}');";
      }
    }
    $runner_file_path = $this->examplesPath . '/tests/runner_plugins.php';
    $result = file_put_contents($runner_file_path, implode(PHP_EOL, $runner_code));
    if (!$result) {
      throw new \RuntimeException(sprintf('Cannot create runner file: %s', $runner_file_path));
    }
  }

  /**
   * Compile the plugin schema file.
   *
   * @param string $id
   *   The plugin ID.
   * @param string $path_to_plugin
   *   The filepath to the plugin definition directory.
   */
  private function compilePlugin(array &$plugin) {
    $this->compilePluginSchema($plugin['id'], $plugin['path']);
    $plugin['has_tests'] = $this->handleTests($plugin['id'], $plugin['path']);

    // Create a service if an event subscriber.
    $instance = $this->pluginsManager->getPluginInstance($plugin['id']);
    if ($instance instanceof EventSubscriberInterface) {
      $plugin_services = [
        'services' => [
          $plugin['id'] . '.plugin' => [
            'class' => '\\' . ltrim($plugin['classname'], '\\'),
            'tags' => [['name' => 'event_subscriber']],
          ],
        ],
      ];
      $this->services = array_merge_recursive($this->services, $plugin_services);
    }
  }

  private function ensureDir($filepath) {
    if (!is_dir($filepath)) {
      mkdir($filepath, 0755, TRUE);
    }
  }

  /**
   * Compile the plugin schema file.
   *
   * @param string $id
   *   The plugin ID.
   * @param string $path_to_plugin
   *   The filepath to the plugin definition directory.
   */
  private function handleTests(string $id, string $path_to_plugin) {
    $this->ensureDir($this->examplesPath . "/tests/plugins/");
    $this->ensureDir($this->examplesPath . "/web/plugins/");

    // Locate the file with the filename of 'test_subject'.
    $subject = array_values(array_filter(scandir($path_to_plugin), function ($path) {
        return pathinfo($path, PATHINFO_FILENAME) === 'test_subject';
      }))[0] ?? NULL;

    $suite_relative_path_final = NULL;
    if ($subject) {
      $extension = pathinfo($subject, PATHINFO_EXTENSION);
      $suite_relative_path_final = "plugins/$id.$extension";
      copy("$path_to_plugin/$subject", $this->examplesPath . "/web/${suite_relative_path_final}");
    }

    if (!is_file($path_to_plugin . '/suite.yml')) {
      return FALSE;
    }

    // The test suite.
    $plugin_suite = Yaml::parseFile($path_to_plugin . '/suite.yml');
    $plugin_suite = array_map(function (array $test) use ($subject, $suite_relative_path_final) {
      if (array_key_exists('visit', $test)) {
        $test['visit'] = str_replace($subject, $suite_relative_path_final, $test['visit']);
      }
      if (array_key_exists('url', $test)) {
        $test['url'] = str_replace($subject, $suite_relative_path_final, $test['url']);
      }

      return $test;
    }, $plugin_suite);
    file_put_contents($this->examplesPath . "/tests/plugins/{$id}.yml", Yaml::dump($plugin_suite, 6));

    return TRUE;
  }

  /**
   * Compile the plugin schema file.
   *
   * @param string $id
   *   The plugin ID.
   * @param string $path_to_plugin
   *   The filepath to the plugin definition directory.
   */
  private function compilePluginSchema(string $id, string $path_to_plugin) {
    if (isset($this->schema['definitions'][$id])) {
      throw new \RuntimeException(sprintf('Plugin ID conflict; %s.definitions.%s already exists', basename($this->masterSchemaPath), $id));
    }

    $before = md5(json_encode($this->schema));

    // The plugin MAY provide new scheme definitions.
    $definitions_schema = $path_to_plugin . '/schema.definitions.json';
    if (file_exists($definitions_schema)) {
      $definitions_schema = $this->loadJson($definitions_schema);
      $conflicting_keys = array_intersect_key($this->schema['definitions'], $definitions_schema);
      if ($conflicting_keys) {
        throw new \RuntimeException(sprintf('The following definitions exist in the master schema and cannot be added by the plugin %s: %s', $id, implode(', ', $conflicting_keys)));
      }
      $this->schema['definitions'] += $definitions_schema;
    }

    // The plugin MAY provide test-level schema.
    $test_schema = $path_to_plugin . '/schema.test.json';
    if (file_exists($test_schema)) {
      $test_schema = $this->loadJson($test_schema);
      $test_schema = $this->handleGlobalSchemaProperties($test_schema);
      $this->schema["items"]["anyOf"][] = $test_schema;
    }

    // The plugin must provide the assertion-level schema.
    $assertion_schema = $path_to_plugin . '/schema.assertion.json';
    if (file_exists($assertion_schema)) {
      $this->schema['definitions'][$id] = [
        'title' => Strings::title("$id Plugin Assertion"),
      ];
      $assertion_schema = $this->loadJson($assertion_schema);
      $assertion_schema = $this->handleGlobalSchemaProperties($assertion_schema);
      $this->schema['definitions'][$id] += $assertion_schema;
      $this->schema['definitions']['find']['oneOf'][1]['items']['oneOf'][] = [
        '$ref' => "#/definitions/$id",
      ];
    }

    if ($before !== md5(json_encode($this->schema))) {
      $this->saveJson($this->generatedSchemaPath, $this->schema);
    }

    // Update the schema in the plugins manager.
    $this->pluginsManager->setSchema($this->loadJson($this->generatedSchemaPath));
  }

  /**
   * Add global vars to a plugin's schema.
   *
   * @param array $schema
   *   The test or assertion schema defined by the plugin.
   *
   * @return array
   *   The schema with globals set.
   *
   * @throws \RuntimeException If the plugin provides any globals.
   */
  private function handleGlobalSchemaProperties(array $schema) {
    $globals = [
      'why' => '#/definitions/why',
      'extras' => '#/definitions/extras',
    ];

    $properties = [];
    foreach ($globals as $property => $ref) {
      if (isset($schema[$property])) {
        throw new \RuntimeException(sprintf('Your plugin schema must not include "%s".', $property));
      }
      $properties[$property] = [
        '$ref' => $ref,
      ];
    }

    // Move globals to the top.
    $schema['properties'] = $properties + $schema['properties'];

    return $schema;
  }

  private function loadJson(string $filepath): array {
    $data = json_decode(file_get_contents($filepath), TRUE);
    if (is_null($data)) {
      throw new \RuntimeException(sprintf('Invalid JSON in %s', $filepath));
    }

    return $data;
  }

  private function saveJson($filepath, $data) {
    $result = file_put_contents($filepath, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    if (!$result) {
      throw new \RuntimeException(sprintf('Could not save %s', $filepath));
    }

    return $this;
  }

  private function generateServicesFile() {
    $result = file_put_contents($this->generatedServicesPath, Yaml::dump($this->services, 4));
    if (!$result) {
      throw new \RuntimeException(sprintf('Could not save %s', $this->generatedServicesPath));
    }

    return $this;
  }

}
