# Set the base URL to use for generating absolute URLs.
base_url: https://intheloftstudios.local.loft

# Set this flag to `true` during development.  If any test suite fails, then the
# runner will stop running any additional suites.
stop_on_failed_suite: true

# Set this flag to `true` during development.  As soon as a single test against
# an URL fails, then the runner will stop.
stop_on_failed_test: true

