-
  why: Demonstrate the Count handler syntax
  url: /test_subject.html
  find:
    -
      dom: h1
      count: 1
    -
      dom: h1
      count: "!= 16"
    -
      xpath: //h1
      count: "1"
    -
      dom: h1
      count: "<2"
    -
      dom: h1
      count: "< 2"
    -
      dom: h5
      count: 0
    -
      dom: li
      count: ">=5"
    -
      dom: li
      count: ">= 5"
    -
      dom: li.emotion
      count: 2
    -
      dom: li
      text: Fear
      count: 1
    -
      dom: li
      text: Morning
      count: 0
    -
      dom: '.sidebar a'
      attribute: href
      matches: /^\/story/
      count: ">=2"

-
  value: 5
  set: maxItems
-
  value: 4
  set: itemCount
-
  why: Demonstrate the Count plugin with interpolation.
  url: /test_subject.html
  find:
    -
      dom: h1
      count: ${maxItems} - ${itemCount}
