<?php
/** AUTOGENERATED DO NOT EDIT */
add_directory(__DIR__ . '/plugins');
load_config('config/local');
run_suite('dom');
run_suite('evaluate');
run_suite('header');
run_suite('import');
run_suite('javascript');
run_suite('json_schema');
run_suite('loop');
run_suite('path');
run_suite('request');
run_suite('sleep');
run_suite('style');
run_suite('xpath');