<?php
/** AUTOGENERATED DO NOT EDIT */
add_directory('/Users/aklump/Code/Packages/php/check_pages/example/tests/plugins');
load_config('config/local');
run_suite('click');
run_suite('javascript');
run_suite('style');