-
  set: alpha
  value: Twilight
-
  set: bravo
  value: ${alpha}
-
  visit: /test_subject.html
  find:
    -
      dom: h1
      is: Twilight
    -
      dom: h1
      is: ${alpha}
    -
      dom: h1
      is: ${bravo}
    -
      set: charlie
      value: ${bravo}
-
  why: Assert we can interpolate with an assertion-level setter from previously.
  visit: /test_subject.html
  find:
    -
      dom: h1
      is: ${charlie}

-
  why: Demonstrate the Value Handler syntax using "why".
  value: lorem ipsum dolar
  set: vars.string
-
  value: ${vars.string}
  is: lorem ipsum dolar
-
  value: ${vars.string}
  is not: foo bar
-
  value: ${vars.string}
  contains: ipsum
-
  value: ${vars.string}
  not contains: alpha
-
  value: ${vars.string}
  matches: /^lorem/
-
  value: ${vars.string}
  not matches: /\d{3}/
-
  value: 123
  set: vars.number
-
  value: ${vars.number}
  is: 123
-
  value: ${vars.number}
  contains: 23
-
  value: ${vars.number}
  matches: /\d{3}/

-
  url: /test_subject.html
  find:
    -
      why: Assert we can perform an assertion "set".
      value: Twilight
      set: control
    -
      why: Assert we can interpolate on "value".
      value: ${control}
      set: control2

-
  why: Assert set values persist to the next test.
  url: /test_subject.html
  find:
    -
      dom: h1
      is: ${control}
    -
      dom: h1
      is: ${control2}
