-
  loop:
    - [ true, w/Javascript ]
    - [ false, No JS ]
-
  why: '${loop.value[1]}: Assert a shorter timeout than request delay will fail the test.'
  expected outcome: failure
  js: '${loop.value[0]}'
  visit: /test_subject.php?timeout=3
  request:
    timeout: 1
-
  why: '${loop.value[1]}: Assert the same request delay without larger timeout passes the test.'
  js: '${loop.value[0]}'
  visit: /test_subject.php?timeout=3
  request:
    timeout: 30
-
  end loop:

-
  why: Assert ${request.method} returns 405
  visit: /test_subject.php
  request:
    methods: [ PATCH, DELETE, HEAD, OPTIONS, TRACE ]
  status: 405

-
  why: Assert request body interpolation is working as expected.
  value: bar
  set: fooValue

-
  why: Assert post with content-type header and body works as expected.
  visit: /test_subject.php
  request:
    method: post
    headers:
      content-type: application/json
    body: '{"foo":"${fooValue}"}'
  find:
    - 'POST'
    - 'content-type: application/json'
    - '{"foo":"bar"}'

-
  why: Assert post encodes body object correctly.
  visit: /test_subject.php
  request:
    method: post
    headers:
      content-type: application/json
    body:
      foo: bar
  find:
    - 'POST'
    - 'content-type: application/json'
    - '{"foo":"bar"}'

-
  visit: /test_subject.php
  request:
    method: GET
    body: 'lorem ipsum'
  find:
    - 'GET'
    - 'lorem ipsum'

-
  why: Assert put with multiple headers and body works as expected.
  visit: /test_subject.php
  request:
    method: PUT
    headers:
      content-type: application/x-www-form-urlencoded
      accept: application/json, application/xml
    body: 'foo=bar&do=re'
  find:
    - 'PUT'
    - "content-type: application/x-www-form-urlencoded"
    - "accept: application/json, application/xml"
    - 'foo=bar&do=re'

-
  why: This will print a debug message in debug mode about un-interpolation.
  visit: /test_subject.php
  request:
    method: GET
    body: 'lorem ${missingVar}'
